services:
  server:
    build: json-server
    environment:
      - FRONT_PORT
      - BACK_PORT
      - PORT=$BACK_PORT
    ports:
      - "$BACK_PORT:$BACK_PORT"
  front: 
    environment:
      - FRONT_PORT
      - BACK_PORT
    build: 
      context: front
      args:
        - BACK_BASE_URL=http://46.101.197.91:$BACK_PORT
        - NEXTAUTH_SECRET=hello
        - NEXTAUTH_URL=http://46.101.197.91:$FRONT_PORT
    ports:
      - "$FRONT_PORT:3000"
