services:
  server:
    build: json-server
    environment:
      - PORT=8080
    ports:
      - 8080:8080
  front: 
    build: 
      context: front
      args:
        - BACK_BASE_URL=http://178.128.204.244:8080
        - NEXTAUTH_SECRET=hello
        - NEXTAUTH_URL=http://178.128.204.244:3000
    ports: 
      - 3000:3000

