services:
  server:
    build: json-server
    environment:
      - PORT=8000
    restart: always
    ports:
      - "8000:8000"
  front: 
    environment:
      - HOST
    restart: always
    build: 
      context: front
      args:
        - BACK_BASE_URL=http://$HOST:8000
        - NEXTAUTH_SECRET=hello
        - NEXTAUTH_URL=http://$HOST:3000
    ports:
      - "3000:3000"
  ngix: 
    depends_on:
      - server
      - front
    restart: always
    build: nginx
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: "certonly --webroot --webroot-path=/var/www/html --email ibrohim7840@gmail.com --agrees-tos --no-eff-email -d pentagol.site -d api.pentagol.site"

