services:
  server:
    build: json-server
    environment:
      - PORT=${BACK_PORT}
    ports:
      - ${BACK_PORT}:${BACK_PORT}
  front: 
    build: 
      context: front
      args:
        - BACK_BASE_URL=${PROTOCOL}://${HOST}:${BACK_PORT}
        - NEXTAUTH_SECRET=hello
        - NEXTAUTH_URL=${PROTOCOL}://${HOST}:${FRONT_PORT}
    ports: 
      - ${FRONT_PORT}:${FRONT_PORT}

