services:
  server:
    build: json-server
    environment:
      - PORT=${BACK_PORT}
    ports:
      - ${BACK_PORT}:${BACK_PORT}
  front: 
    build: 
      context: front
      args:
        - BACK_BASE_URL=http://46.101.197.91:${BACK_PORT}
        - NEXTAUTH_SECRET=hello
        - NEXTAUTH_URL=http://46.101.197.91:3000
    ports: 
      - 3000:3000