services:
  server:
    build: json-server
    environment:
      - PORT=8000
    restart: always
    ports:
      - "8000:8000"
  front: 
    environment:
      - HOST
    restart: always
    build: 
      context: front
      args:
        - BACK_BASE_URL=http://$HOST:8000
        - NEXTAUTH_SECRET=hello
        - NEXTAUTH_URL=http://$HOST:3000
    ports:
      - "3000:3000"
  ngix: 
    depends_on:
      - server
      - front
    restart: always
    build: nginx
    ports:
      - '80:80'
