services:
  server:
    build: json-server
    environment:
      - PORT=8000
    restart: always
    ports:
      - "8000:8000"
  front: 
    environment:
      - HOST
    restart: always
    build: 
      context: front
      args:
        - BACK_BASE_URL=https://api.pentagol.site
        - NEXTAUTH_SECRET=hello
        - NEXTAUTH_URL=http://$HOST:3000
    ports:
      - "3000:3000"
  nginx: 
    depends_on:
      - server
      - front
    restart: always
    build: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


