name: Deploy to Digital Ocean

# on:
#   create:
#     tags:
#       - "*"
on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy-apps:
    name: Build and Deploy Apps
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./json-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pentagol-back:latest
      - name: Build and push front
        uses: docker/build-push-action@v4
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pentagol-front:latest

  deploy-to-digitalocean:
    needs: build-and-deploy-apps
    runs-on: ubuntu-latest
    name: Deploy To Digital Ocean
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy
        uses: digitalocean/app_action@main
        with:
          app_name: Pentagol
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[{
            "name": "",
            "image": {
            "registry_type": "DOCKER_HUB"
            "repository": "pentagol-back"
            "tag":"latest"
            },
            },
            {
            "name":"",
            "image":{
            "registry_type": "DOCKER_HUB"
            "repository": "pentagol-front"
            "tag":"latest"
            }
            }]'
